{"uid":"950715f2ccda5f1c","name":"Verify the account creation functionality.","fullName":"org.api.tests.AuthTest.createAccountTest","historyId":"9f332ada0a3dd0f3252d6838008d1fe5","time":{"start":1755548247606,"stop":1755548249005,"duration":1399},"description":"This test case verifies that a new user account can be created successfully using the SignUp API.","descriptionHtml":"<p>This test case verifies that a new user account can be created successfully using the SignUp API.</p>\n","status":"failed","statusMessage":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-18 20:17:28\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","statusTrace":"java.lang.AssertionError: expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-18 20:17:28\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat org.testng.Assert.assertEquals(Assert.java:666)\n\tat org.api.tests.AuthTest.createAccountTest(AuthTest.java:59)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1755548247100,"stop":1755548247573,"duration":473},"description":"","status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"description":"This test case verifies that a new user account can be created successfully using the SignUp API.","status":"failed","statusMessage":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-18 20:17:28\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","statusTrace":"java.lang.AssertionError: expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-18 20:17:28\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat org.testng.Assert.assertEquals(Assert.java:666)\n\tat org.api.tests.AuthTest.createAccountTest(AuthTest.java:59)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)\n","steps":[],"attachments":[{"uid":"5329453a8fe7218a","name":"Request","source":"5329453a8fe7218a.html","type":"text/html","size":1107},{"uid":"1a8ca20c3a0c3731","name":"HTTP/1.1 500 ","source":"1a8ca20c3a0c3731.html","type":"text/html","size":1402}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"org.api.tests.AuthTest"},{"name":"testClass","value":"org.api.tests.AuthTest"},{"name":"testMethod","value":"createAccountTest"},{"name":"parentSuite","value":"API Test Suite"},{"name":"suite","value":"API Test"},{"name":"subSuite","value":"org.api.tests.AuthTest"},{"name":"host","value":"pkrvmubgrv54qmi"},{"name":"thread","value":"2486@pkrvmubgrv54qmi.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Create Account"},{"name":"epic","value":"Authentication"},{"name":"feature","value":"Auth Service"},{"name":"severity","value":"blocker"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[{"uid":"91b2bb01a1632083","status":"unknown","time":{"start":1755236737955,"stop":1755236737956,"duration":1}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":6,"broken":0,"skipped":0,"passed":0,"unknown":3,"total":9},"items":[{"uid":"21a2a63173ce2af6","reportUrl":"https://rangegowdaym.github.io/apiassured/16//#testresult/21a2a63173ce2af6","status":"failed","statusDetails":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-17 20:18:13\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","time":{"start":1755461892190,"stop":1755461893673,"duration":1483}},{"uid":"26c49573bad02b85","reportUrl":"https://rangegowdaym.github.io/apiassured/15//#testresult/26c49573bad02b85","status":"failed","statusDetails":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-16 20:16:47\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","time":{"start":1755375406013,"stop":1755375407613,"duration":1600}},{"uid":"89a0287ddcbce5cb","reportUrl":"https://rangegowdaym.github.io/apiassured/14//#testresult/89a0287ddcbce5cb","status":"failed","statusDetails":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-15 20:18:04\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","time":{"start":1755289082959,"stop":1755289084497,"duration":1538}},{"uid":"d7971162652a22a2","reportUrl":"https://rangegowdaym.github.io/apiassured/13//#testresult/d7971162652a22a2","status":"failed","statusDetails":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-15 17:38:57\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","time":{"start":1755279536186,"stop":1755279537902,"duration":1716}},{"uid":"88b1b5c549ff503f","reportUrl":"https://rangegowdaym.github.io/apiassured/10//#testresult/88b1b5c549ff503f","status":"failed","statusDetails":"expected [User registered successfully!] but found [{\n    \"timestamp\": \"2025-08-15 15:55:42\",\n    \"status\": 500,\n    \"error\": \"System Error\",\n    \"message\": \"An unexpected error occurred\",\n    \"path\": \"uri=/api/auth/signup\",\n    \"solution\": \"Please try again later or contact support\",\n    \"errorCode\": \"SYS_001\"\n}]","time":{"start":1755273341365,"stop":1755273342881,"duration":1516}},{"uid":"b10d9a80ac9e8871","reportUrl":"https://rangegowdaym.github.io/apiassured/9//#testresult/b10d9a80ac9e8871","status":"unknown","time":{"start":1755270222343,"stop":1755270222343,"duration":0}},{"uid":"5184726adbd99f8a","reportUrl":"https://rangegowdaym.github.io/apiassured/8//#testresult/5184726adbd99f8a","status":"unknown","time":{"start":1755269375348,"stop":1755269375348,"duration":0}},{"uid":"5e60b12318d39bbc","reportUrl":"https://rangegowdaym.github.io/apiassured/7//#testresult/5e60b12318d39bbc","status":"unknown","time":{"start":1755267169534,"stop":1755267169534,"duration":0}}]},"tags":[]},"source":"950715f2ccda5f1c.json","parameterValues":[]}